### ISSUE TITLE
Logo links to http://socialtables.digihey.com instead of https://www.socialtables.com

### ISSUE THREAD

**Issue by simongawlik** [socialtables/apprentice-challenge#3]
This is a duplicate of the same issue in the intern challenge:

The instructions say that the link should go to https://www.socialtables.com but it seems to only go to http://socialtables.digihey.com

I tried starting from https://www.socialtables.com to see if there is another help page that links back to it but I only get to the digihey site.

Is this test supposed to fail in the program that I will submit or am I supposed to test for the digihey link?

**Comment by LaFrish** [comment]
The test still passes for me even though the actual site linked is http://socialtables.digihey.com. I thought it would be an issue at first but was not the case in action.

**Comment by simongawlik** [comment]
Huh... okay. I wonder what the actual test is doing then. I had the driver click through to the class="navbar-brand" link and then confirm the current url of the page that opens but there must be another way to get this result then.

Have you tried testing the test? Like checking if it fails when comparing the link to http://socialtables.digihey.com or even http://www.google.com. I'd be really curious to see what happens. 

Or could there be some rerouting that happens on your internal network (if you're an authenticated user) that doesn't happen for outsiders? I signed up for a user account and tried but it didn't make a difference for me.

Anyway, I know you probably can't give any further hints ;). Thank you for looking into it. I'll see if I can find another way to solve this.

**Comment by LaFrish** [comment]
Lol Well, I am actually taking the challenge too. So we are competitors 😉.... However, I do not mind answering questions as long as the powers that be do not mind helping because in the end this is all a great learning experience.

What say you @ets @hpowers @danmactough ?

**Comment by simongawlik** [comment]
lol my bad. I appreciate your offer but I should probably figure this one out by myself then
